### ISSUE TITLE
questions and many different warnings and errors in the logbook

### ISSUE THREAD

**Issue by blavak68** [tahvane1/jablotron80#132]
Earlier in the past, I tried to find some solution to connect my Jablotron JA-83K with the JA-80T cable to the Homeassitant, but it was successful about a week ago, where it was possible to use this code to make this connection work (through /dev/serial/by-id/usb-Silicon_Labs_JABLOTRON_serial_interface_1-if00-port0)

However, I have a few questions:
------------------------------------------------
- how to use the generated entities for RC remote controls
- I don't know how to find out the status of the AC-88 socket whether it is on or off and I don't know what the generated entity for this device is for when its status never changes
- I have one wireless motion sensor JA-80P, but motion tracking does not work on it, unlike other wired motion sensors
- the generated entities for the keyboard or sirens are for the purpose of guarding the TMP circuit

From time to time I receive such warnings:
-------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:781
Integration: Jablotron 80 (documentation, issues)
First occurred: 06:39:36 (28 occurrences)
no accepted message for sequence:0 received

----------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1134
Integration: Jablotron 80 (documentation, issues)
First occurred: 10:50:54 (1 occurrences)
Invalid message of type State received ed

----------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1126
Integration: Jablotron 80 (documentation, issues)
First occurred: 10:50:54 (1 occurrences)
Unknown message type 0x43 with data 43 00 00 0f 04 00 0a 07 ff received

----------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1126
Integration: Jablotron 80 (documentation, issues)
First occurred: 10:54:08 (1 occurrences)
Unknown message type 0x4 with data 04 00 14 57 ff received

---------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1126
Integration: Jablotron 80 (documentation, issues)
First occurred: 17:37:15 (1 occurrences)
Unknown message type 0x69 with data 69 ff received

---------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1129
Integration: Jablotron 80 (documentation, issues)
First occurred: 18:13:07 (1 occurrences)
Invalid CRC for 8c ed 40 10 00 01 08 00 0a 5b ff

---------------------------------------------------
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1091
Integration: Jablotron 80 (documentation, issues)
Last logged: 11:51:20
Unexpected error processing record: b'\xed@\x00\x00'
Traceback (most recent call last):
  File "/config/custom_components/jablotron80/jablotron.py", line 2596, in processing_loop
    self._process_message(record)
  File "/config/custom_components/jablotron80/jablotron.py", line 2455, in _process_message
    message_type = JablotronMessage.get_message_type_from_record(data,packet_data)
  File "/config/custom_components/jablotron80/jablotron.py", line 1128, in get_message_type_from_record
    if not JablotronMessage.check_crc(record):
  File "/config/custom_components/jablotron80/jablotron.py", line 1091, in check_crc
    assert packet[length-1] == 0xff
AssertionError

----------------------------------------------------
**thx for your great job**

**Comment by mattsaxon** [comment]
Thanks for the feedback, I've left these messages on by default so I can see if others experience the same as me,

However you can remove these messages from your logs by changing the configuration of the integration to 

Tick the "Quieten expected warnings" box on the configuration dialogue
![image](https://user-images.githubusercontent.com/11351127/170870264-8f6f0bde-3770-48f2-935e-9850afe9f56d.png)

**Comment by mattsaxon** [comment]
> I have one wireless motion sensor JA-80P, but motion tracking does not work on it, unlike other wired motion sensors

Wireless devices don't report their status until the system is armed, or in maintenance mode.

**Comment by mattsaxon** [comment]
> the generated entities for the keyboard or sirens are for the purpose of guarding the TMP circuit

Yes those entities cover things like tamper, but also battery low.

**Comment by mattsaxon** [comment]
> how to use the generated entities for RC remote controls

These show status only, you cannot use them to trigger the alarm

**Comment by mattsaxon** [comment]
> I don't know how to find out the status of the AC-88 socket whether it is on or off and I don't know what the generated entity for this device is for when its status never changes

I don't have an AC-88 so I can't comment on how it works. I'd expect it to have an entity if it is detected, but it may be that you haven't enrolled it to the control panel, in which case, it will not show up. How have you got it configured? By the way, it may be that some of the error messages you mention above are related to this device which I'm not aware of, what device number is it enrolled to (if it is enrolled)?

**Comment by blavak68** [comment]
> 

after switch on "Quieten expected warnings" is in logbook only

Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:781
Integration: Jablotron 80 (documentation, issues)
First occurred: 06:39:36 (28 occurrences)
no accepted message for sequence:0 received


regarding AC-88
connection between JA-83K and AC-88 is possible using PGX or PGY output
I  don't know currently how I have the AC-88 connected ... trought PGx/y output or remocte RC but, it is not important
[ac-88_en_mzz55400.pdf](https://github.com/tahvane1/jablotron80/files/8793855/ac-88_en_mzz55400.pdf)

**once again thx for your great work**

**Comment by mattsaxon** [comment]
That warning needs tidying up, I'll keep this issue open and rename it for that.

On the AC-88, if this is attached to PGX/Y, this will be addressed  if/when https://github.com/tahvane1/jablotron80/issues/98 gets addressed.

**Comment by mleitnercom** [comment]
About the `no accepted message for sequence:0 received` warnings specifically (the other lines you pasted are separate problems):

I traced this on my own setup (JA-82K with the JA-82T cable) with debug logging on. They come from the repeating background detail query, the "?" query the integration sends to learn which detectors are currently open. The panel acks that keypress only about one time in six, and when it does ack it answers immediately. In my logs the ack shows up in the very next read cycle in 99.7% of the cases and never later than the third one. When there is no ack, reading longer doesn't help: the panel simply didn't answer that particular keypress, and the next query attempt gets a fresh chance. So a failed round is normal operation here, not a fault. The device reconciliation runs off the rounds that do get acked, and the staleness net from #208 catches whatever slips through.

The only real problem is that the last retry of each query is logged at WARNING. On my system that is roughly 2-3 of these per minute even when nothing is wrong (about 4500 over 30 hours). I changed it so the detail query's miss stays at debug level, while real commands (arm/disarm/settings) keep their WARNING on the final retry, where a missing ack actually means something. That removes the spam without hiding anything useful.

The other warnings you listed (`Unknown message type 0x43`, `Invalid message of type State`) are unrelated and I didn't look into those.
