### ISSUE TITLE
JA-63 "profi" 

### ISSUE THREAD

**Issue by noppeliz** [tahvane1/jablotron80#157]
I'm trying to get the integration to work with a JA-63 hub connected to a usb converter JA-80T but I only get the following error.

`2023-08-21 14:14:38.263 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration jablotron80 which has not been tested by Home Assistant. 
This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-21 14:14:38.264 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. 
This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-21 14:58:54.375 DEBUG (MainThread) [custom_components.jablotron80] JA80CentralUnit function call system_status
2023-08-21 14:58:54.375 INFO (MainThread) [custom_components.jablotron80] Connecting to JA80 via Serial using /dev/ttyUSB0...
2023-08-21 14:58:55.815 DEBUG (MainThread) [custom_components.jablotron80] JA80CentralUnit function call mode
2023-08-21 14:58:55.815 INFO (MainThread) [custom_components.jablotron80] JA80CentralUnit(N/A): initializing mode to Unsplit
2023-08-21 14:58:55.816 INFO (MainThread) [custom_components.jablotron80] initializing
2023-08-21 14:58:55.819 DEBUG (ThreadPoolExecutor-0_0) [custom_components.jablotron80] Loop endlessly reading serial
2023-08-21 14:58:55.842 ERROR (MainThread) [custom_components.jablotron80] Unexpected error processing record: b'\xe0@\x06Y\n\x00\x7f\xff'
Traceback (most recent call last):
  File "/config/custom_components/jablotron80/jablotron.py", line 2596, in processing_loop
    self._process_message(record)
  File "/config/custom_components/jablotron80/jablotron.py", line 2455, in _process_message
    message_type = JablotronMessage.get_message_type_from_record(data,packet_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron80/jablotron.py", line 1126, in get_message_type_from_record
    LOGGER.log(expected_warning_level, f'Unknown message type {hex(record[0])} with data {packet_data} received')
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1555, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
2023-08-21 14:58:56.054 ERROR (MainThread) [custom_components.jablotron80] Unexpected error processing record: b'\xe0@\x06Y\x0b\x00U\xff'
Traceback (most recent call last):
  File "/config/custom_components/jablotron80/jablotron.py", line 2596, in processing_loop
    self._process_message(record)
  File "/config/custom_components/jablotron80/jablotron.py", line 2455, in _process_message
    message_type = JablotronMessage.get_message_type_from_record(data,packet_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron80/jablotron.py", line 1126, in get_message_type_from_record
    LOGGER.log(expected_warning_level, f'Unknown message type {hex(record[0])} with data {packet_data} received')
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1555, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
2023-08-21 14:58:56.367 ERROR (MainThread) [custom_components.jablotron80] Unexpected error processing record: b'\xe0@\x06Y\n\x00\x7f\xff'
Traceback (most recent call last):
  File "/config/custom_components/jablotron80/jablotron.py", line 2596, in processing_loop
    self._process_message(record)
  File "/config/custom_components/jablotron80/jablotron.py", line 2455, in _process_message
    message_type = JablotronMessage.get_message_type_from_record(data,packet_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by noppeliz** [comment]
`2023-08-22 11:14:10.482 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received
2023-08-22 11:14:11.319 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received
2023-08-22 11:14:11.531 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received
2023-08-22 11:14:11.843 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received
2023-08-22 11:14:12.054 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received
2023-08-22 11:14:12.368 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received
2023-08-22 11:14:12.578 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received
2023-08-22 11:14:12.892 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 09 00 67 ff received
2023-08-22 11:14:13.378 DEBUG (MainThread) [custom_components.jablotron80] Short packet, no CRC to check
2023-08-22 11:14:13.378 DEBUG (MainThread) [custom_components.jablotron80] Message of type Beep received a4 ff
2023-08-22 11:14:13.378 INFO (MainThread) [custom_components.jablotron80] Keypad Beep: 0xa4, 4 subtle (short) beeps triggered
2023-08-22 11:14:13.392 DEBUG (MainThread) [custom_components.jablotron80] Message of type Event received e3 01 01 00 04 14 00 3d ff
2023-08-22 11:14:13.392 DEBUG (MainThread) [custom_components.jablotron80] Last Event: 01 01 00 04 14 00
2023-08-22 11:14:13.393 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call battery_low
2023-08-22 11:14:13.393 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): battery_low changed from False to True
2023-08-22 11:14:13.393 DEBUG (MainThread) [custom_components.jablotron80] publishing updates
2023-08-22 11:14:13.394 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call active
2023-08-22 11:14:13.394 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): active changed from False to True
2023-08-22 11:14:13.397 DEBUG (MainThread) [custom_components.jablotron80] publishing updates
2023-08-22 11:14:13.399 DEBUG (MainThread) [custom_components.jablotron80] Zone C action device_activated
2023-08-22 11:14:13.401 WARNING (MainThread) [custom_components.jablotron80] Backup battery fault, 0:JA-80K Control panel, 00:04 Sun 01 Jan
2023-08-22 11:14:13.403 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call last_event
2023-08-22 11:14:13.403 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): last_event changed from Unknown, 0:JA-80K Control panel, 00:04 Sun 01 Jan to Backup battery fault, 0:JA-80K Control panel, 00:04 Sun 01 Jan
2023-08-22 11:14:13.403 DEBUG (MainThread) [custom_components.jablotron80] publishing updates
2023-08-22 11:14:13.407 DEBUG (MainThread) [custom_components.jablotron80] Message of type Event received e7 01 01 00 04 14 00 5f ff
2023-08-22 11:14:13.457 DEBUG (MainThread) [custom_components.jablotron80] Short packet, no CRC to check
2023-08-22 11:14:13.459 DEBUG (MainThread) [custom_components.jablotron80] Message of type Ping received b4 ff
2023-08-22 11:14:13.461 DEBUG (MainThread) [custom_components.jablotron80] Ping Message: 0xb4
2023-08-22 11:14:13.468 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 04 44 0a 00 03 ff received
`

**Comment by mattsaxon** [comment]
This integration has never been tested with JA-6x, looking at the logs, the messages it creates are similar, but different.

To make progress, you’ll need to work out what the messages mean and update the code as appropriate.



Sent from my iPhone

On 22 Aug 2023, at 09:15, noppeliz ***@***.***> wrote:

﻿

2023-08-22 11:14:10.482 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received 2023-08-22 11:14:11.319 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received 2023-08-22 11:14:11.531 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received 2023-08-22 11:14:11.843 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received 2023-08-22 11:14:12.054 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received 2023-08-22 11:14:12.368 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0b 00 33 ff received 2023-08-22 11:14:12.578 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 0a 00 19 ff received 2023-08-22 11:14:12.892 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 05 44 09 00 67 ff received 2023-08-22 11:14:13.378 DEBUG (MainThread) [custom_components.jablotron80] Short packet, no CRC to check 2023-08-22 11:14:13.378 DEBUG (MainThread) [custom_components.jablotron80] Message of type Beep received a4 ff 2023-08-22 11:14:13.378 INFO (MainThread) [custom_components.jablotron80] Keypad Beep: 0xa4, 4 subtle (short) beeps triggered 2023-08-22 11:14:13.392 DEBUG (MainThread) [custom_components.jablotron80] Message of type Event received e3 01 01 00 04 14 00 3d ff 2023-08-22 11:14:13.392 DEBUG (MainThread) [custom_components.jablotron80] Last Event: 01 01 00 04 14 00 2023-08-22 11:14:13.393 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call battery_low 2023-08-22 11:14:13.393 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): battery_low changed from False to True 2023-08-22 11:14:13.393 DEBUG (MainThread) [custom_components.jablotron80] publishing updates 2023-08-22 11:14:13.394 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call active 2023-08-22 11:14:13.394 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): active changed from False to True 2023-08-22 11:14:13.397 DEBUG (MainThread) [custom_components.jablotron80] publishing updates 2023-08-22 11:14:13.399 DEBUG (MainThread) [custom_components.jablotron80] Zone C action device_activated 2023-08-22 11:14:13.401 WARNING (MainThread) [custom_components.jablotron80] Backup battery fault, 0:JA-80K Control panel, 00:04 Sun 01 Jan 2023-08-22 11:14:13.403 DEBUG (MainThread) [custom_components.jablotron80] JablotronControlPanel function call last_event 2023-08-22 11:14:13.403 INFO (MainThread) [custom_components.jablotron80] JablotronControlPanel(0): last_event changed from Unknown, 0:JA-80K Control panel, 00:04 Sun 01 Jan to Backup battery fault, 0:JA-80K Control panel, 00:04 Sun 01 Jan 2023-08-22 11:14:13.403 DEBUG (MainThread) [custom_components.jablotron80] publishing updates 2023-08-22 11:14:13.407 DEBUG (MainThread) [custom_components.jablotron80] Message of type Event received e7 01 01 00 04 14 00 5f ff 2023-08-22 11:14:13.457 DEBUG (MainThread) [custom_components.jablotron80] Short packet, no CRC to check 2023-08-22 11:14:13.459 DEBUG (MainThread) [custom_components.jablotron80] Message of type Ping received b4 ff 2023-08-22 11:14:13.461 DEBUG (MainThread) [custom_components.jablotron80] Ping Message: 0xb4 2023-08-22 11:14:13.468 WARNING (MainThread) [custom_components.jablotron80] Unknown message type 0xe0 with data e0 40 04 44 0a 00 03 ff received

**Comment by noppeliz** [comment]
Have you any tools and tips on how to monitor the data?'

**Comment by mattsaxon** [comment]
For the JA-8x series, the OLink tool has a data monitor in one of the menus. Not sure if that tool is the same for Profi

**Comment by noppeliz** [comment]
something like this
![Jablotron](https://github.com/tahvane1/jablotron80/assets/82360862/009c3200-0453-4e93-bcc7-9e89458dd317)

**Comment by noppeliz** [comment]
no feature found in the application, but could this app see similar
![image](https://github.com/tahvane1/jablotron80/assets/82360862/36a1afb5-3e7a-49fb-a217-2056b0e83015)

**Comment by noppeliz** [comment]
.

**Comment by mattsaxon** [comment]
Yep, that is it. You "just" need to work out the meaning of those packets and correlate them with what is happening. How much effort this is will depend on how similar it is to the JA80. When I started writing the JA80 integration I started with this and then wrote the code around what I found here (well I actually used a different tool, not knowing this existed!)

**Comment by noppeliz** [comment]
ok, thanks for the advice. let's see if this comes to anything result :-)
