### ISSUE TITLE
Unexpected error:bytearray(b'\xc6\xff')

### ISSUE THREAD

**Issue by mazzy89** [tahvane1/jablotron80#44]
I have found in the logs more than 3285 occurrences of this error

```
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:2080
Integration: Jablotron 80 ([documentation](https://github.com/tahvane1/jablotron80), [issues](https://github.com/tahvane1/jablotron80/issues))
First occurred: February 19, 2022, 9:19:11 PM (3285 occurrences)
Last logged: 7:48:20 PM

Unexpected error:bytearray(b'\xc6\xff'): Traceback (most recent call last): File "/config/custom_components/jablotron80/jablotron.py", line 2077, in processing_loop self._process_message(record) File "/config/custom_components/jablotron80/jablotron.py", line 1954, in _process_message beep = JablotronKeyPress.get_beep_option(data[0]& 0x0f) File "/config/custom_components/jablotron80/jablotron.py", line 771, in get_beep_option return JablotronKeyPress._BEEP_OPTIONS[code] KeyError: 6
```

No idea what it is because I do not know the internals of Jablotron but I guess is something related with the latest updates.

**Comment by mattsaxon** [comment]
Fixed in https://github.com/tahvane1/jablotron80/pull/48
